Update fetch2.yaml

diff --git a/.github/workflows/fetch2.yaml b/.github/workflows/fetch2.yaml
--- a/.github/workflows/fetch2.yaml
+++ b/.github/workflows/fetch2.yaml
@@ -1,167 +1,115 @@
-name: Fetch, dedup, split, extract ip
+name: "IPextract Factory Expanded"
 
 on:
   workflow_dispatch:
-  #schedule:
-    #- cron: '49 2,8,14,20 * * *'
-# push:
-#    branches: [ main ]
+  schedule:
+    - cron: '49 2,8,14,20 * * *'
 
 jobs:
   update:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
     steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-    - name: Set up Python
-      uses: actions/setup-python@v4
-      with:
-        python-version: '3.x'
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
 
-    - name: Set up Git
-      run: |
-        git config --global user.name 'github-actions[bot]'
-        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+      - name: Prepare Workspace
+        run: |
+          mkdir -p split splitorg archive archiveorg splitbytype/split
+          touch proxies.txt ss.txt unique_add.txt new_proxies.txt nodup_proxies.txt
+          touch splitbytype/ss.txt
 
-    - name: Fetch, decode if needed, and combine file content
-      run: |
-        # Function to safely append content to a file
-        append_to_file() {
-          local content="$1"
-          local file="$2"
-          echo "$content" >> "$file"
-        }
-
-        # Initialize or clear the proxies.txt file
-        > proxies.txt
-        
-        # Function to check if a string is base64 encoded
-        is_base64() {
-          local string="$1"
-          echo "$string" | base64 -d > /dev/null 2>&1
-          return $?
-        }
-        
-        # List of URLs to fetch from
-        urls=(
-          "https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/configtg.txt"
-          "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/irc.txt"
-          "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/mci.txt"
-          "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/mkb.txt"
-          "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/hy2.txt"
-          "https://raw.githubusercontent.com/yebekhe/TVC/main/subscriptions/xray/normal/mix"
-          "https://raw.githubusercontent.com/yebekhe/V2Hub/main/merged"
-          "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vmess"
-          "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vless"
-          "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/mix"
-          "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/donated"
-          "https://raw.githubusercontent.com/itsyebekhe/HiN-VPN/main/subscription/normal/mix"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollectorVpnclashfa/main/ss_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollectorVpnclashfa/main/vmess_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollectorVpnclashfa/main/vless_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollectorVpnclashfa/main/trojan_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollector_mahsaserver/main/ss_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollector_mahsaserver/main/vmess_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollector_mahsaserver/main/vless_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollector_mahsaserver/main/trojan_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2RayAggregator/master/sub/sub_merge.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2ray-Config-Lite/main/All_Configs_Sub.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/All_Configs_Sub.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2ray-Configs/main/All_Configs_Sub.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollector/main/ss_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollector/main/vmess_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollector/main/vless_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2rayCollector/main/trojan_iran.txt"
-          "https://raw.githubusercontent.com/coldwater-10/V2Hub2/main/Split/Normal/vmess"
-          "https://raw.githubusercontent.com/coldwater-10/V2Hub/main/Split/Normal/vless"
-          "https://raw.githubusercontent.com/coldwater-10/V2Hub/main/Split/Normal/reality"
-          "https://raw.githubusercontent.com/coldwater-10/V2Hub1/main/Split/Normal/trojan"
-          "https://raw.githubusercontent.com/coldwater-10/V2Hub1/main/Split/Normal/shadowsocks"
-          "https://raw.githubusercontent.com/coldwater-10/V2Hub3/main/merged"
-          "https://raw.githubusercontent.com/coldwater-10/V2Hub4/main/merged"
-          "https://raw.githubusercontent.com/Surfboardv2ray/Proxy-sorter/main/submerge/IR.txt"
-          "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/ir/mixed"
-        )
-        
-        # Fetch from each URL, decode if necessary, and append to proxies.txt
-        for url in "${urls[@]}"; do
-          echo "Fetching from $url"
-          content=$(curl -s "$url")
-          if [ -n "$content" ]; then
-            if is_base64 "$content"; then
-              echo "Decoding Base64..."
-              decoded_content=$(echo "$content" | base64 -d 2>/dev/null)
-              if [ $? -eq 0 ]; then
-                append_to_file "$decoded_content" proxies.txt
+      - name: Fetch All Sources
+        run: |
+          > proxies.txt
+          urls=(
+            "https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/configtg.txt"
+            "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/irc.txt"
+            "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/mci.txt"
+            "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/mkb.txt"
+            "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/hy2.txt"
+            "https://raw.githubusercontent.com/yebekhe/TVC/main/subscriptions/xray/normal/mix"
+            "https://raw.githubusercontent.com/yebekhe/V2Hub/main/merged"
+            "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vmess"
+            "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vless"
+            "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/mix"
+            "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/donated"
+            "https://raw.githubusercontent.com/itsyebekhe/HiN-VPN/main/subscription/normal/mix"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollectorVpnclashfa/main/ss_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollectorVpnclashfa/main/vmess_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollectorVpnclashfa/main/vless_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollectorVpnclashfa/main/trojan_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollector_mahsaserver/main/ss_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollector_mahsaserver/main/vmess_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollector_mahsaserver/main/vless_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollector_mahsaserver/main/trojan_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2RayAggregator/master/sub/sub_merge.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2ray-Config-Lite/main/All_Configs_Sub.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2ray-Config/main/All_Configs_Sub.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2ray-Configs/main/All_Configs_Sub.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollector/main/ss_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollector/main/vmess_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollector/main/vless_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2rayCollector/main/trojan_iran.txt"
+            "https://raw.githubusercontent.com/coldwater-10/V2Hub2/main/Split/Normal/vmess"
+            "https://raw.githubusercontent.com/coldwater-10/V2Hub/main/Split/Normal/vless"
+            "https://raw.githubusercontent.com/coldwater-10/V2Hub/main/Split/Normal/reality"
+            "https://raw.githubusercontent.com/coldwater-10/V2Hub1/main/Split/Normal/trojan"
+            "https://raw.githubusercontent.com/coldwater-10/V2Hub1/main/Split/Normal/shadowsocks"
+            "https://raw.githubusercontent.com/coldwater-10/V2Hub3/main/merged"
+            "https://raw.githubusercontent.com/coldwater-10/V2Hub4/main/merged"
+            "https://raw.githubusercontent.com/Surfboardv2ray/Proxy-sorter/main/submerge/IR.txt"
+            "https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/ir/mixed"
+          )
+          for url in "${urls[@]}"; do
+            content=$(curl -sL "$url")
+            if [ -n "$content" ]; then
+              if [[ "$content" =~ ^[A-Za-z0-9+/]*={0,2}$ ]]; then
+                echo "$content" | base64 -d >> proxies.txt 2>/dev/null || echo "$content" >> proxies.txt
               else
-                echo "Failed to decode from $url"
+                echo "$content" >> proxies.txt
               fi
-            else
-              echo "raw content, moving on."
-              append_to_file "$content" proxies.txt
+              echo "" >> proxies.txt
             fi
-            # Add a newline after each file to separate content
-            append_to_file "" proxies.txt
-          else
-            echo "No content received from $url"
+          done
+
+      - name: Run Core Processing
+        run: |
+          python no_dup.py || echo "error in no_dup"
+          python extract_ips.py || echo "error in extract_ips"
+          python replace_ips.py || echo "error in replace_ips"
+          python splitbytype.py || echo "error in splitbytype"
+          python ssrandom.py || echo "error in ssrandom"
+          python split_file.py || echo "error in split_file"
+          python splitorg_file.py || echo "error in splitorg_file"
+
+      - name: Git Push
+        run: |
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          
+          # Чистка тяжелых файлов перед пушем
+          python -c "
+          import os
+          for root, dirs, files in os.walk('.'):
+              for f in files:
+                  if f.endswith('.txt'):
+                      p = os.path.join(root, f)
+                      if os.path.exists(p) and os.path.getsize(p) > 90*1024*1024:
+                          with open(p, 'r', encoding='utf-8') as file: lines = file.readlines()
+                          with open(p, 'w', encoding='utf-8') as file: file.writelines(lines[:350000])
+          "
+          
+          git add .
+          if ! git diff --cached --quiet; then
+            git commit -m "Update extended proxy list"
+            git push
           fi
-        done
-
-        echo "Fetch and combine process completed."
-
-    - name: Run no_dup script
-      run: python no_dup.py
-
-    - name: Run IP extraction script
-      run: python extract_ips.py
-
-    - name : Run IP replacement script
-      run: python replace_ips.py
-
-    - name: Run splitbytype script
-      run: python splitbytype.py
-
-    - name: List splitbytype directory contents
-      run: |
-        echo "Main splitbytype directory:"
-        ls -la splitbytype
-        echo "Split subfolder:"
-        ls -la splitbytype/split
-        
-    - name: List split directory contents before
-      run: ls -la split
-    
-    - name: Run random line selector script
-      run: python ssrandom.py
-
-    - name: List splitbytype directory contents after random selection
-      run: ls -la splitbytype
-
-    - name: Archive, clear, and split new proxies
-      run: python split_file.py
-
-    - name: List split directory contents after
-      run: ls -la split
-      
-    - name: List splitorg directory contents before
-      run: ls -la splitorg
-
-    - name: Archive, clear, and split orgproxies
-      run: python splitorg_file.py
-
-    - name: List splitorg directory contents after
-      run: ls -la splitorg
-
-    - name: Commit and push if there are changes
-      run: |
-        git add proxies.txt unique_add.txt new_proxies.txt nodup_proxies.txt
-        git add -A split/
-        git add archive/**/*.txt
-        git add -A splitorg/
-        git add archiveorg/**/*.txt
-        git add -A splitbytype/
-        git add -A splitbytype/split/
-        git add splitbytype/ssrandom.txt
-        git diff --quiet && git diff --staged --quiet || (git commit -m "Update proxies and IPs, archive old files, create new split files, and add random selection" && git push)
